name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7' # 사용하는 Flutter 버전으로 변경

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Firebase Config
        run: |
          mkdir -p lib/config
          cat > lib/config/firebase_config.dart << EOF
          import 'package:firebase_core/firebase_core.dart';

          class FirebaseConfig {
            static const FirebaseOptions options = FirebaseOptions(
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            );
          }
          EOF

      - name: Build Web
        run: flutter build web --release --base-href /juwon_portfolio/

      - name: Add .nojekyll
        run: echo > build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRET_KEY_NAME }} # repository에서 사용할 시크릿 키 이름
          publish_dir: build/web
          publish_branch: gh-pages